INSERT INTO COUNTRY_MASTER VALUES (1,'+91' ,'INDIA');
INSERT INTO COUNTRY_MASTER VALUES (2,'+1','USA');

INSERT INTO STATE_MASTER VALUES (1,1,'BIHAR' );
INSERT INTO STATE_MASTER VALUES (2,1,'KARNATAKA');
INSERT INTO STATE_MASTER VALUES (3,2,'NEW YORK');
INSERT INTO STATE_MASTER VALUES (4,2,'NEW JESRSY');

INSERT INTO CITY_MASTER VALUES (1,'GOPALGANJ',1);
INSERT INTO CITY_MASTER VALUES (2,'PATNA',1);
INSERT INTO CITY_MASTER VALUES (3,'BANGALURU',2);
INSERT INTO CITY_MASTER VALUES (4,'MYSORE',2);
INSERT INTO CITY_MASTER VALUES (5,'MAYWOOD',3);
INSERT INTO CITY_MASTER VALUES (6,'WESTWOOD',3);
INSERT INTO CITY_MASTER VALUES (7,'SOUTHWOOD',4);
INSERT INTO CITY_MASTER VALUES (8,'EASTWOOD',4);


